function node = vhybrid_node(state, acceleration, steering_angle, parent_id, ...
    g_cost, h_cost, indices, node_id)
%VHYBRID_NODE 构造带速度和时间的 V-Hybrid A* 节点。
%
% 输入：
%   state          - [x,y,theta,v,t]，单位 m、rad、m/s、s。
%   acceleration   - 节点使用的加速度，单位 m/s^2。
%   steering_angle - 节点使用的前轮转角，单位 rad。
%   parent_id      - 父节点编号；起点为 0。
%   g_cost/h_cost  - 累积代价和启发代价。
%   indices        - [x_index,y_index,yaw_index,velocity_index,time_index]。
%   node_id        - 当前节点编号。
%
% 输出：
%   node           - 固定字段节点结构体，包含连续状态、离散索引、控制量、
%                    父节点和 f=g+h 代价。
%
% 算法逻辑：
%   连续状态用于运动学和碰撞检查；五维离散索引用于 Closed 集合查重。
%   时间索引和速度索引被显式保留，避免把同一位置的不同时间/速度状态错误合并。

if nargin == 0
    state = zeros(1,5);
    acceleration = 0;
    steering_angle = 0;
    parent_id = 0;
    g_cost = 0;
    h_cost = 0;
    indices = zeros(1,5);
    node_id = 0;
end

state = double(state(:).');
indices = double(indices(:).');
if numel(state) ~= 5 || numel(indices) ~= 5
    error('Summon:VNode:InvalidShape', 'state 和 indices 必须各包含 5 个元素。');
end

node = struct( ...
    'node_id', double(node_id), ...
    'x', state(1), ...
    'y', state(2), ...
    'theta', state(3), ...
    'v', state(4), ...
    't', state(5), ...
    'acceleration', double(acceleration), ...
    'steering_angle', double(steering_angle), ...
    'parent_id', double(parent_id), ...
    'g_cost', double(g_cost), ...
    'h_cost', double(h_cost), ...
    'f_cost', double(g_cost + h_cost), ...
    'x_index', indices(1), ...
    'y_index', indices(2), ...
    'yaw_index', indices(3), ...
    'velocity_index', indices(4), ...
    'time_index', indices(5), ...
    'direction', 0, ...
    'travelled_distance', 0);
end
